// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"WaitCommandUntilPromiseSettled","status":true,"description":"非同期処理が完了するまで、イベントコマンドを待機する機能を提供します","parameters":{}},
{"name":"AtsumaruApi","status":true,"description":"アツマールAPIを利用可能にするプラグインです","parameters":{"commentGposVerbose":"false","commentGposMode":"v3","commonOnComment":"","commentCommonOnComment":"","commandCommonOnComment":"","createdAtCommonOnComment":"","isPostCommonOnComment":"","isGiftCommonOnComment":"","nameCommonOnComment":"","pointCommonOnComment":"","thanksCommonOnComment":"","replyCommonOnComment":"","thanksSettings":"","autoThanks":"true","thanksText":"","thanksImage":"","clapThanksText":"","clapThanksImage":"","giftThanksText":"","giftThanksImage":""}}
];
